apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quay-perf-test
rules:
- apiGroups: ["extensions", "apps", "batch"]
  resources: ["deployments", "jobs", "pods", "services", "jobs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
